name: reviewdog
on: [pull_request]
jobs:
  credo:
    name: runner / credo
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: credo
        uses: hauleth/reviewdog-action-credo@v1
        with:
          github_token: ${{ secrets.github_token }}
      - name: credo-pr-review
        uses: hauleth/reviewdog-action-credo@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
